defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout

      - run:
          name: Build
          command: |
            echo "build" > fiz-o-build.txt

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:8.9

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy
          command: |
            ls -la
            echo "deploy"
            cat fiz-o-build.txt

workflows:
  version: 2
  build-and-test:
    jobs:
      - build:
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
