defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:8.9

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - node-modules-cache-{{ checksum ".circleci/config.yml" }}-{{ checksum "package.json" }}

      # - restore_cache:
      #     keys:
      #       - meteor-{{ checksum ".circleci/config.yml" }}-{{ checksum ".meteor/release" }}

      - run:
          name: Build
          command: |
            echo "build" > fiz-o-build.txt

  deploy:
    <<: *defaults
    docker:
      - image: circleci/node:8.9

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Deploy
          command: |
            echo "deploy"
            cat fiz-o-build.txt

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
